### ISSUE TITLE
AttributeError: module 'sopel.tools' has no attribute 'time'

### ISSUE THREAD

**Issue by ckraft** [sopel-irc/sopel-youtube#24]
When running the youtube plugin on Sopel 7.0.4 on Python 3.8.2 I ran into an issue with the call to the function format_time.

Here is the error I received:

[2020-07-18 16:38:53,125] sopel.bot            ERROR    - Unexpected error (module 'sopel.tools' has no attribute 'time') from Krafter at 2020-07-18 16:38:53.125421. Message was: https://www.youtube.com/watch?v=PCg0iCbg3pA
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sopel/bot.py", line 606, in call
    exit_code = func(sopel, trigger)
  File "/usr/local/lib/python3.8/dist-packages/sopel/coretasks.py", line 1016, in decorated
    return function(bot, trigger, match=match)
  File "/home/yori/.sopel/plugins/youtube/youtube.py", line 144, in get_info
    _say_result(bot, trigger, match.group(2), include_link=False)
  File "/home/yori/.sopel/plugins/youtube/youtube.py", line 181, in _say_result
    message += " | " + _parse_published_at(bot, trigger, snippet["publishedAt"])
  File "/home/yori/.sopel/plugins/youtube/youtube.py", line 222, in _parse_published_at
    return tools.time.format_time(bot.db, bot.config, nick=trigger.nick,
AttributeError: module 'sopel.tools' has no attribute 'time'

I was able to fix it in my copy by adding the following import:
from sopel.tools import time

**Comment by dgw** [comment]
This sounds like [the "submodules are added to the package namespace" trap](http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-submodules-are-added-to-the-package-namespace-trap).

More specifically for this case, you've probably excluded a plugin from Sopel's standard set that normally imports `sopel.tools.time` (meaning it's available anyway, despite not being imported by `youtube`, because of the above trap).

**Comment by dgw** [comment]
Right, so #25 should fix this. If you can give it a try to confirm it fixes the problem in your environment, I'll release a new version to PyPI. (I tested locally, too, but it's always good to get confirmation from the issue reporter!)

**Comment by ckraft** [comment]
This fix works for me. Thanks for looking at it. I managed to fix it for myself in my local copy but figured I would share in case someone else ran into this.
