### ISSUE TITLE
Error on Auto Playlists

### ISSUE THREAD

**Issue by RustyBower** [sopel-irc/sopel-youtube#37]
Looks like there's an issue with autogenerated playlists?

[2021-05-12 19:04:10,627] sopel.bot            ERROR    - Unexpected error ('channelId') from RustyCloud at 2021-05-12 19:04:10.626938. Message was: https://www.youtube.com/watch?v=XhzpxjuwZy0&list=RDCLAK5uy_nvu_HUY0DPNpbB_V0moUfs9s5zABAF8xQ&index=26
Traceback (most recent call last):
  File "/home/sopel/.local/lib/python3.7/site-packages/sopel/bot.py", line 606, in call
    exit_code = func(sopel, trigger)
  File "/home/sopel/.local/lib/python3.7/site-packages/sopel/coretasks.py", line 1016, in decorated
    return function(bot, trigger, match=match)
  File "/home/sopel/.local/lib/python3.7/site-packages/sopel_modules/youtube/youtube.py", line 291, in get_playlist_info
    _say_playlist_result(bot, trigger, match.group(2))
  File "/home/sopel/.local/lib/python3.7/site-packages/sopel_modules/youtube/youtube.py", line 334, in _say_playlist_result
    if snippet['channelId'] in AUTO_PLAYLIST_OWNER_IDS:
KeyError: 'channelId'

**Comment by dgw** [comment]
I did some research into this, but haven't gotten to implementing more playlist ID filters yet.

[This](https://gist.github.com/xdavidhu/136c7dfa9247e4883c1e4dc7a77350e6) gives some details about special playlists, but it's probably a better fix to `try`/`except` for specific pieces of metadata and skip if not provided in the response.

At one point I had a more comprehensive overview of playlist ID formats, but I couldn't find it again today. 😦
