### ISSUE TITLE
some links cause double output

### ISSUE THREAD

**Issue by ghost** [sopel-irc/sopel-youtube#43]
```
07:07:58 <~xnaas> https://www.youtube.com/watch?v=uBU4dvlL07Y&list=PLKtIcOP0WvJACfz11Vbp7Yz8mAcJ-l4KK
07:07:58 <Sackbot> [YouTube] ⁨Visiting⁩ | Automatic Playlist/Mix
07:07:58 <Sackbot> [YouTube] ⁨Visiting @anthpo⁩ | 2021-08-06 16:04 | Channel: ⁨Joel Haver⁩ | 5m 33s
```
sopel: v7.1.6
sopel-youtube: v0.4.1

**Comment by ghost** [comment]
Not sure if related in any way...but originally when this link was posted last night, it went like this:

```
21:01:10 <%feek> the full "visiting playlist" in order https://www.youtube.com/watch?v=uBU4dvlL07Y&list=PLKtIcOP0WvJACfz11Vbp7Yz8mAcJ-l4KK
21:02:10 <Sackbot> Unexpected error (The read operation timed out) from feek at 2021-11-08 03:02:10.323384. Message was: youtube.com/watch?v=uBU4dvlL07Y
21:02:11 <Sackbot> [YouTube] ⁨Visiting⁩ | Automatic Playlist/Mix
```

default.error.log:

```
[2021-11-07 21:02:10,323] sopel.bot            ERROR    - Unexpected error (The read operation timed out) from feek at 2021-11-08 03:02:10.323384. Message was: youtube.com/watch?v=uBU4dvlL07Y
Traceback (most recent call last):
  File "/home/xnaas/sackbot2/lib/python3.9/site-packages/sopel/bot.py", line 763, in call_rule
    rule.execute(sopel, trigger)
  File "/home/xnaas/sackbot2/lib/python3.9/site-packages/sopel/plugins/rules.py", line 1057, in execute
    exit_code = self._handler(bot, trigger)
  File "/home/xnaas/sackbot2/lib/python3.9/site-packages/sopel/plugins/rules.py", line 1608, in execute_handler
    return handler(bot, trigger, match=trigger)
  File "/home/xnaas/sackbot2/lib/python3.9/site-packages/sopel_modules/youtube/youtube.py", line 173, in get_video_info
    _say_video_result(bot, trigger, match.group(1), include_link=False)
  File "/home/xnaas/sackbot2/lib/python3.9/site-packages/sopel_modules/youtube/youtube.py", line 179, in _say_video_result
    result = bot.memory['youtube_api_client'].videos().list(
  File "/home/xnaas/sackbot2/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/xnaas/sackbot2/lib/python3.9/site-packages/googleapiclient/http.py", line 883, in execute
    resp, content = _retry_request(
  File "/home/xnaas/sackbot2/lib/python3.9/site-packages/googleapiclient/http.py", line 195, in _retry_request
    raise exception
  File "/home/xnaas/sackbot2/lib/python3.9/site-packages/googleapiclient/http.py", line 172, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/xnaas/sackbot2/lib/python3.9/site-packages/httplib2/__init__.py", line 1708, in request
    (response, content) = self._request(
  File "/home/xnaas/sackbot2/lib/python3.9/site-packages/httplib2/__init__.py", line 1424, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/xnaas/sackbot2/lib/python3.9/site-packages/httplib2/__init__.py", line 1405, in _conn_request
    content = response.read()
  File "/usr/lib/python3.9/http/client.py", line 465, in read
    return self._readall_chunked()
  File "/usr/lib/python3.9/http/client.py", line 572, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.9/http/client.py", line 555, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.9/http/client.py", line 515, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

**Comment by dgw** [comment]
See readme and <kbd>Ctrl</kbd>-<kbd>F</kbd> for `playlist_watch` setting.

The timeout error is a separate issue, but probably should be handled somewhere.

**Comment by ghost** [comment]
> See readme and Ctrl-F for `playlist_watch` setting.

🙈
