### ISSUE TITLE
Unable to install if google-api-python-client is not already installed

### ISSUE THREAD

**Issue by maxpowa** [sopel-irc/sopel-youtube#9]
Caused by setup.py importing the module to grab the version, which in turn tries to import `apiclient` from `google-api-python-client`

```
$ pip install sopel_modules.youtube
Collecting sopel-modules.youtube
  Downloading sopel_modules.youtube-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-l8j2yh0q/sopel-modules.youtube/setup.py", line 7, in <module>
        from sopel_modules.youtube import __version__
      File "/tmp/pip-build-l8j2yh0q/sopel-modules.youtube/sopel_modules/youtube/__init__.py", line 8, in <module>
        from .youtube import *
      File "/tmp/pip-build-l8j2yh0q/sopel-modules.youtube/sopel_modules/youtube/youtube.py", line 12, in <module>
        import apiclient.discovery
    ImportError: No module named 'apiclient'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-l8j2yh0q/sopel-modules.youtube/
```

**Comment by freeboson** [comment]
Yes, this is silly. You could use bumpversion to handle this properly, instead of loading the module you're about to install just to know what version it is!

@embolalia
